---
:S:
  :method: :show
  :params: {}
:I:
  :method: :new
  :params:
    :columns: 0
    :rows: 1
:L:
  :method: :paint
  :params:
    :range_h: !ruby/range
      begin: 0
      end: 0
      excl: false
    :range_v: !ruby/range
      begin: 1
      end: 1
      excl: false
    :colour: 2
:H:
  :method: :paint
  :params:
    :range_h: !ruby/range
      begin: 0
      end: 1
      excl: false
    :range_v: !ruby/range
      begin: 2
      end: 2
      excl: false
    :colour: 3
:V:
  :method: :paint
  :params:
    :range_h: !ruby/range
      begin: 0
      end: 0
      excl: false
    :range_v: !ruby/range
      begin: 1
      end: 2
      excl: false
    :colour: 3
:C:
  :method: :paint
  :params:
    :range_h: !ruby/range
      begin: 0
      end: .inf
      excl: false
    :range_v: !ruby/range
      begin: 0
      end: .inf
      excl: false
    :colour: 0
